---
sidebar: sidebar 
permalink: task-add-gcp-bucket.html 
keywords: google cloud storage buckets, google cloud storage, add buckets 
summary: Google Cloud Storage 시스템을 시스템 페이지에서 사용할 수 있는 경우 NetApp 콘솔에서 직접 추가 버킷을 추가할 수 있습니다. 
---
= Google Cloud Storage 버킷 추가
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Google Cloud Storage 시스템을 시스템 페이지에서 사용할 수 있는 경우 NetApp 콘솔에서 직접 추가 버킷을 추가할 수 있습니다.

.단계
. 시스템 페이지에서 Google Cloud Storage 시스템을 두 번 클릭하여 Google Cloud Storage 버킷 개요 페이지를 보고 *버킷 추가*를 클릭합니다.
+
_버킷 추가_ 페이지가 표시됩니다.

. _프로젝트 세부 정보_ 섹션에 필요한 정보를 입력하세요.
+
** *버킷 이름* - 버킷에 사용할 이름을 입력하세요. https://cloud.google.com/storage/docs/buckets#naming["명명 요구 사항에 대한 Google Cloud 문서를 참조하세요."^] .
** *Google 프로젝트* - 버킷의 소유자가 될 Google 프로젝트를 선택하세요.  이는 콘솔 에이전트가 배포된 기본 프로젝트일 수도 있고 다른 프로젝트일 수도 있습니다.  드롭다운 목록에 추가 프로젝트가 보이지 않으면 NetApp 콘솔 서비스 계정을 다른 프로젝트와 아직 연결하지 않은 것입니다.  Google Cloud 콘솔로 이동하여 IAM 서비스를 열고 프로젝트를 선택합니다.  해당 프로젝트에 NetApp 콘솔 역할이 있는 서비스 계정을 추가합니다.  각 프로젝트마다 이 단계를 반복해야 합니다.  참고: 이것은 NetApp 콘솔에 대해 설정한 서비스 계정입니다. https://docs.netapp.com/us-en/console-setup-admin/task-set-up-permissions-google.html#set-up-permissions-for-the-connector["이 페이지에 설명된 대로"^] .
** *레이블* - 라벨은 Google Cloud 리소스에 대한 메타데이터입니다.  버킷을 생성할 때 최대 10개의 라벨 키:값 쌍을 추가할 수 있습니다. https://cloud.google.com/compute/docs/labeling-resources["레이블에 대한 자세한 내용은 Google Cloud 문서를 참조하세요."^] .


. _위치_ 섹션에서 버킷이 생성될 위치 유형과 지역(들)을 선택합니다.  세 가지 유형의 위치 중에서 선택할 수 있습니다.
+
[cols="35,65"]
|===
| "위치 유형"을 선택하면... | 그런 다음 선택하세요... 


| 지역 | "사용 가능한 지역" 필드의 단일 지역입니다. 


| 이중 지역  a| 
"사용 가능한 위치" 필드에서 지리적 위치(단일 대륙)를 선택한 다음, "사용 가능한 지역" 필드에서 두 개의 지역을 선택합니다.

15분이라는 목표 시간 내에 새로 작성된 모든 객체에 대한 지리적 중복성을 보장하려면 "터보 복제"를 활성화할 수 있습니다.



| 다중 지역 | "사용 가능한 다중 지역" 필드의 지리적 다중 지역입니다. 
|===
+
클라우드 스토리지 데이터는 업로드하는 즉시 적어도 한 곳의 지리적 장소 내 두 개 이상의 영역에 중복된다는 점에 유의하세요. https://cloud.google.com/storage/docs/locations["버킷 위치에 대한 자세한 내용은 Google Cloud 문서를 참조하세요."^] .

. _저장 클래스_ 섹션에서 버킷의 객체에 사용할 저장 클래스를 선택합니다.  4가지 저장 클래스 중에서 선택할 수도 있고, _자동 클래스_를 선택하면 Google에서 필요에 따라 클래스를 조정합니다.
+
** *표준* - 자주 액세스하는 데이터("핫" 데이터) 또는 짧은 기간 동안만 저장된 데이터에 가장 적합합니다.
** *니어라인* - 접근 빈도가 낮은 데이터를 저장하기 위한 저렴하고 내구성이 뛰어난 저장 서비스입니다.
** *콜드라인* - 매우 저렴하고 내구성이 뛰어나며 자주 접근하지 않는 데이터를 저장하는 스토리지 서비스입니다.
** *아카이브* - 데이터 보관, 온라인 백업, 재해 복구를 위한 가장 저렴하고 내구성이 뛰어난 스토리지 서비스입니다.
** *자동 클래스* - 각 객체의 액세스 패턴에 따라 버킷의 객체를 적절한 스토리지 클래스로 자동 전환합니다.
+
각 보관 클래스마다 비용과 검색 수수료가 다릅니다. https://cloud.google.com/storage/docs/storage-classes["스토리지 클래스에 대한 자세한 내용은 Google Cloud 문서를 참조하세요."^] .



. _보호_ 섹션에서 버킷의 객체를 보호하기 위해 데이터 보호 도구를 사용할지, 아니면 데이터 암호화 구성을 사용하여 데이터에 대한 액세스를 보호할지 선택합니다.
+
*데이터 보호 도구*

+
** *없음* - 기본적으로 버킷에는 보호 도구가 활성화되어 있지 않습니다.
** *객체 버전 관리* - 객체 버전 관리란 동일한 버킷에 객체의 여러 버전을 보관하는 수단입니다.  버킷은 라이브 객체 버전을 업데이트, 교체 또는 삭제할 때마다 최신이 아닌 객체 버전을 유지 관리하여 객체의 보호된 버전을 지속적으로 유지 관리합니다.  "개체 버전 관리"를 선택하면 두 가지 옵션을 지정할 수 있습니다.
+
*** *객체당 최대 버전 수* - 생성될 객체당 현재가 아닌 버전의 수를 입력하세요.
*** *현재가 아닌 버전 만료 시점* - 오래되고 현재가 아닌 객체를 제거하기까지의 일수를 입력합니다.


** *보존 정책* - 보존 정책은 버킷에 있는 모든 현재 및 미래 객체가 보존 정책에서 정의한 기간에 도달할 때까지 삭제되거나 교체되지 않도록 보장합니다.  "보존 정책"을 선택하면 두 가지 옵션을 지정할 수 있습니다.
+
*** *객체 보관 기간* - 객체를 보관할 초, 일, 월 또는 년 수를 입력합니다.
*** *기간* - 시간이 초, 일, 월 또는 년인지 선택하세요.
+
개체 버전 관리 및 보존 정책 보호 도구는 동시에 활성화할 수 없습니다.  Google Cloud 문서를 참조하세요. https://cloud.google.com/storage/docs/object-versioning["객체 버전 관리에 대한 자세한 정보"^] , 그리고 https://cloud.google.com/storage/docs/bucket-lock["보존 정책에 대한 자세한 정보"^] .





+
*데이터 암호화 도구*

+
** *Google에서 관리하는 암호화 키* - 기본적으로 Google에서 관리하는 암호화 키는 데이터를 암호화하는 데 사용됩니다.
** *고객 관리 암호화 키* - 기본 Google 관리 암호화 키 대신 고객이 직접 관리하는 키를 사용하여 데이터를 암호화할 수 있습니다.  고객이 직접 관리하는 키를 사용할 계획이라면 이 페이지에서 키를 선택할 수 있도록 이미 키를 생성해 두어야 합니다.
+
키는 버킷과 같은 프로젝트에 있을 수도 있고, 다른 프로젝트를 선택할 수도 있습니다.

+
Google Cloud 문서를 참조하세요. https://cloud.google.com/storage/docs/encryption/default-keys["Google 관리 암호화 키에 대한 자세한 정보"^] , 그리고 https://cloud.google.com/storage/docs/encryption/customer-managed-keys["고객 관리 암호화 키에 대한 자세한 정보"^] .



. *추가*를 클릭하면 버킷이 생성됩니다.

